### ISSUE TITLE
Add Content to Infopages

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#189]
Most of what comprises Info about Giveth and the DApp has been realized according to Marko‘s mockups. We are still missing the text content that should go in some places. I tried to avoid „Lorem Ipsum“ placeholders but also other text elements should be checked for content.

###  List of places that have content missing:

- [x] Landing Page Texts (Home)
- [x] About Us (Mission & Vision)
- [x] About Us (History)
- [x] About Us (Team)
- [x] Partnerships
- [x] FAQ (see #114)

**Comment by willyogo** [comment]
Added some draft copy for About us (mission & vision) and removed the lorum ipsum copy from Partnerships (didn't think the 'more info' section was necessary, at least at this time (less is more!))

**Comment by papermache** [comment]
Added FAQ to Staging for review.

https://docs.google.com/document/d/1A_jzYO-m9LutopKDfaCUExKHXw6Q-S4zgwAy6lrmaTw/edit?usp=sharing

**Comment by papermache** [comment]
@papermache @Danibelle need mission and vision.

**Comment by papermache** [comment]
Mission: Our mission is to connect people, ideas, and resources to facilitate and incentivize social impact. We are not content with the current non-profit industry, and we are committed to developing a better, decentralized alternative. Solidarity not charity.
Giveth hopes to be the place where every organization that wants to support public goods is able to COOPERATE and COORDINATE in doing so. 
This focus on cooperation between our allies is the only attitude that is required to join this organization. Otherwise we prefer to have a diversity of opinion and temperament styles. :-D
