### ISSUE TITLE
Reflect categories in backend

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#266]
- [x] Prepare list of categories on frontend
- [ ] Review
- [ ] Use these categories on backend

**Comment by jamespfarrell** [comment]
This is currently done in src/utils/constants.js:
`export const categoryList = [
  { name: 'nonprofit', value: 'Non-profit' },
  { name: 'covid19', value: 'COVID-19' },
  { name: 'technology', value: 'Technology' },
  { name: 'other', value: 'Other' }
]
`

I propose to create a GraphQL end point, that returns something similar from the database, along with categoryIds
When someone creates a project, they then (unbeknownst to them) send these categoryIds back to the server to be saved from the projects

**Comment by jamespfarrell** [comment]
@markoprljic I guess these are reflected bottom left on high 5 screen? 
![image](https://user-images.githubusercontent.com/10499048/103461644-377a8280-4d20-11eb-9e87-0eb97987d7e3.png)

**Comment by markoprljic** [comment]
Pasting suggested categories from @jamespfarrell 

![unknown](https://user-images.githubusercontent.com/5704285/103461775-2c742200-4d21-11eb-9ba2-3f8c85e3f753.png)
<img width="465" alt="Image 2021-01-02 at 5 37 42 pm" src="https://user-images.githubusercontent.com/5704285/103461791-46ae0000-4d21-11eb-90dd-7d7e85139a98.png">
<img width="472" alt="Image 2021-01-02 at 5 37 55 pm" src="https://user-images.githubusercontent.com/5704285/103461793-4877c380-4d21-11eb-86e7-093f653cca27.png">

Following up from Discor convo, I'd go with as many categories as possible, and keep the names short because they'll better fit on the front-end.

From Impact example I'd shorten some of the categories to one word. Here's the list:

- Agriculture
- Air
- Biodiversity
- Climate
- Inclusion
- Education
- Employment
- Energy
- Finance
- Health
- Infrastructure
- Land
- Oceans
- Pollution
- Real Estate
- Waste
- Water

Additionally, we need more categories such as:

- Non-profit
- Technology
- Community
- Food
- Housing

[SDG's from](https://docs.google.com/spreadsheets/d/1wNUlY49XwA-QNYw9EX9utIUQZ9gAc_7DJSAOHK9zxJM/edit) @geleeroyale doc are already covered in the list above. 

If anyone has more categories to suggest please post them here. Thanks.

**Comment by markoprljic** [comment]
> @markoprljic I guess these are reflected bottom left on high 5 screen?
> ![image](https://user-images.githubusercontent.com/10499048/103461644-377a8280-4d20-11eb-9e87-0eb97987d7e3.png)

Yes and elsewhere on the Project details and on the Create Project flow.
<img width="595" alt="Image 2021-01-02 at 5 39 02 pm" src="https://user-images.githubusercontent.com/5704285/103461852-a1475c00-4d21-11eb-88d6-2e9921947b25.png">

**Comment by jamespfarrell** [comment]
I will add the source of each category to the item in the database, so we can do smart things in the future....

**Comment by Danibelle** [comment]
These are the 9 we condensed for Gaia Protection.. 
![Gaia Goals](https://user-images.githubusercontent.com/39466970/103544390-e61fdf80-4e54-11eb-8ad5-06fb16b4ab97.png)


![SDG Goals](https://user-images.githubusercontent.com/39466970/103544407-ed46ed80-4e54-11eb-9765-77e12522c367.png)

**Comment by markoprljic** [comment]
Thanks @Danibelle I updated the list above with few more categories from your list https://github.com/Giveth/giveth-2/issues/266#issuecomment-753495801
