### ISSUE TITLE
Import Giveth 1 campaigns into Giveth 2

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#313]
## 📋 Anything to add?
@Danibelle signalled that this is a feature that she would like to see.

Amin sent me this link or feathers to get details.

We could probably easily wrap feathers with a GraphQL query or potentially create an import script.

## ⏰ Urgency/Deadline/Blockers?
Not urgent right now

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by Danibelle** [comment]
Thanks @jamespfarrell !

This is the first part, importing from G1 to G2. It would be epic if something were added to the G1 that allows the Campaign Manager to select where else it should appear, with G2 being the first enabled yet configuring it so that as Whitelabel versions come up, they can be added to the selection options.
Longer term request would be that Projects created on G2 have an option to also appear on G1 (or elsewhere), for Milestone creation on them there to increase transparency and accountability.

**Comment by jamespfarrell** [comment]
@Danibelle Is this something that is wanted?

**Comment by Danibelle** [comment]
Thanks @jamespfarrell 

We are planning to contact the project owners and invite them to create their project anew at giveth.io

I know I have many active projects at beta.giveth.io that I would personally like moved so the answer is..

Yes, and it will probably need to be by request or in a batch that has been requested..

**Comment by jamespfarrell** [comment]
Ok I'm closing this for now, we can re-open it when there is something actionable....
