### ISSUE TITLE
User ID replication? Says I'm the owner of a project I didn't create

### ISSUE THREAD

**Issue by laurenluz** [Giveth/giveth-2#459]
I think this is related to issue #370 

@willyogo created a project, but it lists me (on my discord) as the owner:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/4dae1881-cf48-49e8-9dfb-95a75cb186c9)

## 📋 Anything to add?

Also, this may or may not be relevant... when I was playing around signing in with different accounts I noticed that no matter what means I used to sign in (Torus/facebook, Torus/discord, Metamask) it always shows the same three donations under "my donations" but there isn't the same overlap with projects I created... Projects I created when signed in with Metamask exist only there and projects I created when signed in with Discord exist only there... Not sure if this is related... I guess my donations are based off the wallet address and my projects are based off of User ID?

**Comment by jamespfarrell** [comment]
Please log out, and then back in again.

**Comment by laurenluz** [comment]
It still says I created that project - should that have changed with the fix? Or it's just fixed, as in, "won't happen again"

![image](https://user-images.githubusercontent.com/75490971/107067824-73808780-67a5-11eb-9d4b-79c0a6930002.png)

**Comment by jamespfarrell** [comment]
Lauren your userId was saved in the database as the user who owns this, and how made the update.

So it's acting correctly right now. It could be that your userId was added to this due to a previous bug.

I have manually updated this back to Willy's in the database now. Let's keep and eye out and see if there's a way to accidentally take ownership of someone's project, but I suspect this will be resolved now, and it's just a hangover of a previous issue that's now fixed.
