### ISSUE TITLE
Users should be able to delete or at least disable a project

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/giveth-2#486]

**Comment by mateodaza** [comment]
Is this priority for release of follow up?

**Comment by mateodaza** [comment]
visual issue fixed, coming next update

**Comment by divine-comedian** [comment]
@mateodaza  I'm running into an error when trying this out, could be related to a separate bug but when I go into a project that I created I can edit and click the `deactive project` button. it reacts and shows `activate project` so that seems to work well, but the project however continues to show up on the projects page.. I investigated further what happens  and I receive a console error: 
![image](https://user-images.githubusercontent.com/67759413/111477559-9cc9f700-8705-11eb-92dc-0be409081fcf.png)


![image](https://user-images.githubusercontent.com/67759413/111476426-87080200-8704-11eb-9485-80c700172f30.png)

I installed a new OS on my computer since creating the project but I've imported the same brave account and same metamask address. My profile info is still recognized on Giveth but apart from not having permission to edit it seems that my projects no longer show up in the 'my projects' page.

**Comment by divine-comedian** [comment]
I'm going to create a separate issue for this bug. I wanted to give the whole context at least here what happened when I tried testing this issue.

**Comment by mateodaza** [comment]
I'm aware of this issue, actually thought about it during my sleep lol - what's happening is that as the page is being rendered from the server what you see is not up to date. Thanks for noticing!

**Comment by mateodaza** [comment]
> I'm going to create a separate issue for this bug. I wanted to give the whole context at least here what happened when I tried testing this issue.

Oh I didn't see the error, I suppose that if you log out and log in again it'd work? - It's still an issue that but just wondering

**Comment by jamespfarrell** [comment]
This was a data issue, there was some manual mirgations done on the database and the statusId wasn't updated from null to 5 on older projects. The query failed frontend when no statusId was found for one of the projects.

I have manually updated the data in the database, and added query to the impact-graph migrations to catch this in future.

**Comment by divine-comedian** [comment]
I've retested this again, all my projects show up now but when I deactivate the project it still shows up on the projects menu.. you can see in the console it gives the isActive value as false..

![image](https://user-images.githubusercontent.com/67759413/111536083-2d252d80-8740-11eb-85b6-3729792c635c.png)
![image](https://user-images.githubusercontent.com/67759413/111536236-5f368f80-8740-11eb-9a97-0f06f1a1ec15.png)

![image](https://user-images.githubusercontent.com/67759413/111536186-4e861980-8740-11eb-9954-ffd4a95498a0.png)

**Comment by divine-comedian** [comment]
Okay testing again - Deactivated project, it no longer shows up on the projects page and I try to navigate to it using the slug 
![image](https://user-images.githubusercontent.com/67759413/111548059-8432fe80-8750-11eb-9b41-93c975cea5bc.png)


<br> 
Okay and upon further investigation I went ahead to Re-activate my project, it shows up again in the projects page but I try to click learn more and I still get the pop-up from the original screenshot saying this project is cancelled..

![image](https://user-images.githubusercontent.com/67759413/111548393-091e1800-8751-11eb-894a-5b1ec240fb9a.png)
![image](https://user-images.githubusercontent.com/67759413/111548686-716cf980-8751-11eb-97d5-d300732faea0.png)

<br>

*Side-note FEEDBACK - it still shows this project as 'ACTIVE' on the my projects page even if the project is 'deactivated'. 
![image](https://user-images.githubusercontent.com/67759413/111548173-ac226200-8750-11eb-8043-d043c6fa6ec3.png)

**Comment by divine-comedian** [comment]
UPDATE - Mateo got it fixed, activating and deactivating now works, projects are removed from view and added back in accordingly, and the detailed project view allows or disable viewing access accordingly as well. Nice WORK!
