### ISSUE TITLE
Torus defaults as the only Wallet option once used once

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#546]
First i sign in with Torus... then I sign out

<img width="321" alt="Screen Shot 2021-02-14 at 5 44 46 PM" src="https://user-images.githubusercontent.com/14945613/107891419-d5b45780-6f1e-11eb-9bf1-058f3bb67711.png">

Now i want to sign in with metamask
<img width="240" alt="Screen Shot 2021-02-14 at 5 44 52 PM" src="https://user-images.githubusercontent.com/14945613/107891433-e95fbe00-6f1e-11eb-80ba-ba8b64163818.png">

But i have no choice... i only get Torus... I have a project that used metamask and want to edit my project... but i can't! 

Frown-y face!

**Comment by divine-comedian** [comment]
@mateodaza  I signed in with torus, then signed out. I clicked sign in again and there's no option for metamask, the torus permission pop up is the only thing that happens when I try to log in the second time. 

![image](https://user-images.githubusercontent.com/67759413/108248753-41b2dd80-7122-11eb-8e48-5e03d118716a.png)

**Comment by mateodaza** [comment]
This is a weird one, will take a look

**Comment by divine-comedian** [comment]
Fixed! I can sign-out on Torus and then when I click Sign in it will let me choose between Torus or Metamask. works like a dream!
