### ISSUE TITLE
Update Impact Graph to return the project slug

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#55]

**Comment by papermache** [comment]
fork impact graph and bring it into the organizaion.

**Comment by mateodaza** [comment]
@CamiloTD have a working version of this in our fork at https://github.com/mateodaza/impact-graph where we assign a slug for the project in the creation flow, there is also a script to assign a slug to previously created projects.

I'll work in the front-end so the fetch in /project and /donate routes use the slug instead of ID.
As soon as I'm done and our back-end is updated I'll make a PR to close this
