### ISSUE TITLE
Footer links "Blog" and "Contact" don't open in new tabs

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#550]
## 📋 Anything to add?

The footer links Blog and Contact don't open in new windows while the rest of the links with the same arrow symbol do open in new windows.

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/ce1f5497-8095-4300-8bc9-e025df10c329)

**Comment by jamespfarrell** [comment]
@markoprljic I believe we agreed that no links will open in a new window as that is best practice user experience?

**Comment by markoprljic** [comment]
Contact should open in the same window. Blog and all external links which are clearly indicated that way can open in new window.

**Comment by geleeroyale** [comment]
Alright - will fix link for blog.

It is considered an anti-pattern (more a matter of taste probably, but I have read that before) to let links open in a new tab because that functionality exists in any browser and can be invoked by the user as they wish.

It makes sense for external links to open in new tab since they are marked in that way.

**Comment by markoprljic** [comment]
That's correct Kay, it is antipattern and all links should open in same window. Since we clearly marked external links I consider this not breaking the rule, but I could be wrong. 

Not a first world problem tho 🙂
