### ISSUE TITLE
Multiple messages once you change network and/or wallet with Metamask

### ISSUE THREAD

**Issue by jamespfarrell** [Giveth/giveth-2#561]

**Comment by divine-comedian** [comment]
Okay so upon testing this I do in fact get one message only if I change my network while logged in on metamask. The funny thing is I can't read it because the metamask window blocks where it pops up. Also it looks like something refreshes instantly when I change network thereby clearing my screen of the pop up message quicker than I could click out of metamask to read what the message says.
![image](https://user-images.githubusercontent.com/67759413/112317968-f04ac080-8c82-11eb-8836-9e303681aaaf.png)

When I change wallets while still on metamask I will only get one message, which is good. 

![image](https://user-images.githubusercontent.com/67759413/112318447-6bac7200-8c83-11eb-8956-bbbcc742d506.png)

**Comment by mateodaza** [comment]
I read on metamask docs that is a good practice to reload the site when the network is changed (which makes all sense) I can put a little delay so the message is visible

**Comment by divine-comedian** [comment]
Looks great - resolved as intended. 
![image](https://user-images.githubusercontent.com/67759413/112653473-d5b04d00-8e24-11eb-846c-7f7742970780.png)
