### ISSUE TITLE
Project View - UI

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-2#61]
This ticket is to create the frontend for the project view page and display corresponding details for each project.

Page should display the following elements of a project:
Project image
Project name
Organization or Admin name
Location
Description

The 'DONATE' section and CTA is covered in a separate ticket.

When a user visits the url for a project (https://v2.giveth.io/projects/[project name]), they see the project view page with the above details for the project.

![Project view](https://user-images.githubusercontent.com/26232238/87248730-599de280-c418-11ea-929c-212da9c91fdc.png)

**Comment by willyogo** [comment]
Out of scope for now: Donations and Updates tabs

**Comment by brymut** [comment]
Added the initial work project page, which can be accessed via /projects/[project-title-slug]. The project pages are currently created via the Gatsby API “createPages” which queries the backend for project data and generates pages via a project page template. However, currently, the only data we get is the project title and description which is the only data collected via the ` addProjectSimple` mutation. We need the full addProject mutation so that we can get more data to use on the project page. 
So I think currently, this is kind of blocked.

**Comment by GriffGreen** [comment]
hide the heart and arrow for now

**Comment by papermache** [comment]
@mateodaza will try to move this to In Progress for Sunday.
