### ISSUE TITLE
Mobile - Subscribe via email not optimized + capitalization

### ISSUE THREAD

**Issue by krrisis** [Giveth/giveth-2#688]
## 📋 Anything to add?

Prob better on two lines so that it is fully readable, incl the confirmation message after subscribing? 

Also: change 'Newsletter' to newsletter :)

![image](https://user-images.githubusercontent.com/6533925/112200051-1f274f00-8c0f-11eb-9ade-9ece323c312b.png)

## 🎉 Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍ Reviewer

@

**Comment by laurenluz** [comment]
this is much improved, but "Newsletter" is still captialized... also the "thank you for" is right-justified... not sure if that was intentional. I think right or center justification is better!

![image](https://user-images.githubusercontent.com/75490971/117203191-f8cb0680-adab-11eb-9032-765e7b9a9ab4.png)
