### ISSUE TITLE
Consider adding stronger Usability testing procedures into our development process

### ISSUE THREAD

**Issue by GriffGreen** [Giveth/giveth-2#713]
@Jeff_Piestrak on twitter was courageous enough to give us constructive feedback around usability:

https://twitter.com/Jeff_Piestrak/status/1375101914984165378?s=20

> I see a big need for presenting these tools w/out jargon & acronyms, focusing more on leading non-technical users through each step.
> 
> That includes developing personas (https://interaction-design.org/literature/topics/personas) and usability tests (https://interaction-design.org/literature/topics/usability-testing).
>

**Comment by Danibelle** [comment]
Assigning myself here because I'm pulling this issue into the Governance Call agenda for priorization discussion based on comments from @jamespfarrell in Discord, I resonate with it also  :)

Concerned about feedback from users who can't represent their own issues in Dev Calls, we can't put the onus on the messenger (Griff in this instance) to track, categorize, prioritize, follow up etc ...
