### ISSUE TITLE
There should always be default one (1) update when project is created 

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#719]
## 📋 Anything to add?
All new projects have initial "Project launched" status update, therefor the Updates tab should display number "1" in the counter.

![Image 2021-03-27 at 4 06 27 pm](https://user-images.githubusercontent.com/5704285/112725077-9bbf7380-8f16-11eb-8b42-075040c3c7bf.jpg)

**Comment by markoprljic** [comment]
Also, this blue indicator is meant to be for new and "unread" updates BUT maybe we don't want to implement that now. That being said we can either make the counter in brackets (1) or apply the same style with the blue circle to Donations tab.

**Comment by markoprljic** [comment]
Like this 
![Image 2021-03-27 at 6 37 50 pm](https://user-images.githubusercontent.com/5704285/112729262-915ba480-8f2b-11eb-9431-c1ad3e076ce3.jpg)

**Comment by geleeroyale** [comment]
Expanding on this, probably should make an epic for updating the updates 😜 

1 - Updates are buggy - I always get the same dates (the current date when I am watching!) on all campaigns and their individual updates. Without dates they are unfortunately useless because you can't see the frequency of updates.
2 - People don't use them, maybe we can expand on this feature a bit. I.e. show the latest update together with the project description? To inventivize more we could display a banner after a certain period of time that shows "This project had no update in a while ...."
3 - Donors should get notified when a project gets updated

**Comment by markoprljic** [comment]
I've been thinking about all this yesterday and planning to update it in front-end.

Open to hear more suggestions from others.

**Comment by markoprljic** [comment]
Created new issue for this. https://github.com/Giveth/giveth-2/issues/831
