### ISSUE TITLE
Remove the badge showing amount raised on Project cards?

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#780]
## 📋 Anything to add?
We're not using the Raised badge on project cards, we're not showing the amount a project has raised. Is that correct? 
All projects just show as "New". 

Do we plan to show the amounts and if not should we remove that badge?

## 🔗 Work doc - inspirational links

![Image 2021-04-15 at 8.34.13 pm.jpg](https://images.zenhubusercontent.com/5cc090818b624e26c3734d75/466f7607-fb47-4e7a-b80d-d16a19682bc8)

**Comment by laurenluz** [comment]
I don't have a strong opinion on if should show the amounts or not, but I do think that we should change the functionality of the "new" circle at the very least. 

So it says "new" when it's first added and then after a week (or some predetermined time) the "new" goes away.

**Comment by markoprljic** [comment]
Yeah, maybe we should keep the NEW label and remove the amounts for time being. We can always switch that on I guess when we feel comfortable displaying such information. We do show it on project details page but maybe doesn't have to be visible on the front page immediately, especially since donation amounts are low at the beginning.

**Comment by WhyldWanderer** [comment]
As a project owner, I would prefer to keep the amount raised in the project description page so that it encourages donors to learn more about the project to find this information if they want to know. 

As a donor, there is already functionality to sort projects by amount raised so it isnt necessary to display that info on a label. 

Once the "new" label expires, we can use this space for the verified project label?

**Comment by laurenluz** [comment]
Yessss! +1 on using the space for the "verified" label, if applicable later. Great idea @WhyldWanderer

**Comment by markoprljic** [comment]
Keep the label to display NEW projects, remove it after a project is 1 week old.
