### ISSUE TITLE
Design for new Support page

### ISSUE THREAD

**Issue by markoprljic** [Giveth/giveth-2#830]
## 📋 Anything to add?

Put individual support methods like the contact form and make github issue button in their respective places where they make sense, but also make a new support page where we group all of them together with the typeform flow as suggested above - in that way people can see at a glance what options are available.

Reasons people would provide feedback or need to contact us:

Problem with project creation flow or urgent need of support
-Chat support widget

Report a bug or issue (UX/UI, txn issues, hearts not working, etc
-Form that triggers an appropriately labelled issue in github

Request a new feature
-Form that triggers a message in a ‘#requested features’ channel in discord?
-Form that triggers an appropriately labelled issue in github?

General inquiries
-Form that triggers a message in a ‘#feedback’ channel in discord?

General suggestions or feedback
-Form that triggers a message in a ‘#feedback’ channel in discord?

Related Issue [#177](https://github.com/Giveth/giveth-planning/issues/177)

**Comment by WhyldWanderer** [comment]
ive been playing with the github and discord integrations on the typeform. And I have been able to successfully trigger github issues with correct labelling and discord messages in one of my play servers

I think it will be great to have all of this in one place..

The thing that Im learning is that the trigger happens when the form is submitted therefore it is impossible (as far as i know) to have multiple triggers from one form.

On the contact page we can have 4 buttons for 
Request Feature
Issue or Bug
Inquiries that require a response
General Suggestions/Feedback

Each button would trigger a small popup form with one or two questions and once that is submitted it will trigger the desired outcome.

Request Feature - trigger github issue with Requested Feature Label
Issue or Bug - trigger github issue with Bug label
Inquiries that require a response can go to a discord channel or to an email address
General Suggestions or feedback can go into a 'feedback' channel on our discord
we wouldnt even need any logic within the forms and having seperate forms will allow us to use them in the areas that they are relevant to the application.. like request a feature could be used in one of our banners where the user can then quickly and easily request a feature without having to move through a longer form flow.. 

just 4 different very simple forms that trigger different things

![image](https://user-images.githubusercontent.com/74267818/117213984-911bb800-adb9-11eb-9381-8f1e481e8b4d.png)

![image](https://user-images.githubusercontent.com/74267818/117214072-9973f300-adb9-11eb-8c76-e919e5714c2b.png)

**Comment by markoprljic** [comment]
Support page demo here https://www.figma.com/proto/FBqHg0UfeuaIueDEZG0tBS/Giveth.io?page-id=970%3A1&node-id=5624%3A1856&viewport=-405%2C-2849%2C0.09304647147655487&scaling=min-zoom

Modal for each support type @mateodaza should change the icon, title and description text. 

Success modal is used the same we use on Contact page. @Giveth/communication if want to change the text please respond here.

![Image 2021-05-20 at 2 47 01 pm](https://user-images.githubusercontent.com/5704285/118981115-4d5cad00-b97a-11eb-91a8-f02a41e70507.jpg)

![Image 2021-05-20 at 2 47 17 pm](https://user-images.githubusercontent.com/5704285/118981135-52b9f780-b97a-11eb-996f-e3afe1e2403b.jpg)

**Comment by laurenluz** [comment]
@markoprljic looks awesome! I have some suggested edits for text. @WhyldWanderer you want to review?

Report an Issue
Having problems with our site? Is something not functioning as expected?

Request a New Feature
Want to see a new feature on Giveth? Are we missing a critical functionality?

Ask us a Question
Do you have a specific question or a general inquiry? Want our team to get back to you with a response?

Leave Feedback
Let us know how your experience was! How can we improve?

**Comment by markoprljic** [comment]
Fixed. Thanks @laurenluz  Ask a Question I just left out the second sentence.

**Comment by geleeroyale** [comment]
Very cool - thanks for mocking this up!
