### ISSUE TITLE
'Learn more' button on my projects in my profile doesn't work.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/giveth-2#855]
On my profile page I am viewing my accounts and the button `learn more` does nothing... If i press `Edit` however it does take me into the project edit page correctly.. 

Also if we could change the text here to be more general like 'View Project' because in this context to 'learn more' about my own project doesn't make sense.
on next.giveth with clean cache and cookies, signed in with MM

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/7817ceba-743a-4b42-b6f4-d61e124a8c80)

**Comment by laurenluz** [comment]
It also doesn't work to click on the project card - FYI... can't just click to view your own project from the "my projects" page

**Comment by MerlinEgalite** [comment]
@laurenluz I'm not sure if it makes sense to be able to directly click on the card if 2 buttons are already implemented. Or Perhaps I don't understand your point 🤔😅

**Comment by mateodaza** [comment]
fixed it haha it was an issue with the old way of navigating - I'm with Merlin on that as the user has two main options to choose, but yeah!

**Comment by laurenluz** [comment]
It works properly now if you click "Learn More" on the projects under "My Projects" page - testing on next using Brave

As per the clicking on the card thing... well, from the regular projects page, it is possible to click anywhere on the care to get redirected to the project's page. This is not the case under "my projects". I think it should be consistent in the DApp otherwise it is a bit awkward/confusing to the user (i.e. ME 🤣)

**Comment by mateodaza** [comment]
alright alright you win this one! 🙆🏼‍♂️
